CREATE DATABASE OKEntregas

USE OKEntregas

CREATE TABLE Usuarios
(
		IdUsuario INT IDENTITY PRIMARY KEY NOT NULL,
		Nome VARCHAR(200) NOT NULL,
		Email VARCHAR(200) UNIQUE NOT NULL,
		Senha VARCHAR(200) NOT NULL,
		TipoUsuario BIT NOT NULL
);
